export const exampleData: any = [
  {
    id: "1",
    name: "Middle of central park",
    lat: 40.785091,
    lng: -73.968285,
    notes: "Howdy adventurer! My name is Ben, and welcome to Figure8 Maps. Planning your next adventure? You’re in the right place. Click the other pins to learn more.",
    category: "sightseeing",
  },
  {
    id: "2",
    name: "Times square",
    lat: 40.758,
    lng: -73.9855,
    notes: "You can drop a pin anywhere in the world, which is why pins are based on Earth’s coordinates. When dropping a pin, you can search a location, or type in the coordinates directly.",
    category: "sightseeing",
  },
  {
    id: "3",
    name: "Empire state building",
    lat: 40.748817,
    lng: -73.985428,
    notes: "Pins have useful info. When dropping a pin, you pick its category (for example, Hiking) and you’ll be able to add other info as well (like Hike Length). You can also type some notes (this hike is easy peasy).",
    category: "sightseeing",
  },
  {
    id: "4",
    name: "Soho area",
    lat: 40.7245908,
    lng: -74.00191740000001,
    notes: "You can always delete maps and pins. To delete a map, click Edit next to My Maps. To delete a pin, click on it and you’ll see a delete button.",
    category: "sightseeing",
  },
  {
    id: "5",
    name: "Brooklyn bridge",
    lat: 40.7061,
    lng: -73.9969,
    notes: "What does your next adventure look like? I have a feeling you have some wonderful new maps in your future. ",
    category: "sightseeing",
  },
  {
    id: "6",
    name: "Central park south",
    lat: 40.7661912,
    lng: -73.97729919999999,
    notes: "With Figure8 Maps, you have the freedom to build your own custom interactive maps anywhere in the world. Just create a map and drop some pins. Oh, and when you’re logged in, your maps are saved for you and you can come back anytime.",
    category: "sightseeing",
  },
];
