export const exampleData: any = [
  {
    id: "1",
    name: "Central Park",
    lat: 40.785091,
    lng: -73.968285,
    notes: "Iconic park in NYC",
    category: "sightseeing",
  },
  {
    id: "2",
    name: "Times Square",
    lat: 40.758,
    lng: -73.9855,
    notes: "Famous intersection in NYC",
    category: "sightseeing",
  },
  {
    id: "3",
    name: "Empire State Building",
    lat: 40.748817,
    lng: -73.985428,
    notes: "Iconic skyscraper",
    category: "sightseeing",
  },
  {
    id: "4",
    name: "Statue of Liberty",
    lat: 40.6892,
    lng: -74.0445,
    notes: "Symbol of freedom",
    category: "sightseeing",
  },
  {
    id: "5",
    name: "Brooklyn Bridge",
    lat: 40.7061,
    lng: -73.9969,
    notes: "Historic bridge",
    category: "sightseeing",
  },
  {
    id: "6",
    name: "Broadway",
    lat: 40.759,
    lng: -73.9845,
    notes: "Famous theater district",
    category: "sightseeing",
  },
];
